Repository Tool-daruda/daruda-frontend, pull requests merged in 2025-03, with the labels that each got.

#177 [Fix] 로그인 토큰 갱신 로직 수정
  public/svgs/img_popupmodal2_84.svg
  src/apis/index.ts
  src/assets/svgs/ImgPopupmodal284.tsx
  src/assets/svgs/index.ts
  src/components/layout/MyPageLayout.tsx
  src/pages/login/KakaoAuth.tsx
  src/pages/login/KakaoRedirectHandler..tsx
  src/pages/login/KakaoRedirectHandler.tsx
  src/pages/login/apis/api.ts
  src/pages/login/apis/getKakaoData.ts
  src/pages/login/apis/postKakaoToken.ts
  src/pages/login/apis/quaries.ts
  src/routes/Router.tsx
  src/utils/.keep
Labels: ⚒️ Fix, 🔥 Refactor, 찬영

#182 [Feat] Tool 목록 페이지가 메인 화면이 되도록 라우팅을 변경한다.
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/header/category/Category.styled.ts
  src/routes/Router.tsx
Labels: 📍 Feat, 고은

#187 [Fix] 헤더 레이어 수정 및 커뮤니티 불필요한 코드를 정리한다.
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/pages/community/Community.tsx
  src/pages/toolList/components/searchBar/SearchBar.styled.ts
Labels: ⚒️ Fix, 고은

#183 [Feat] 북마크시 토스트 팝업이 뜨도록 설정한다
  src/components/common/toast/Toast.styled.ts
  src/components/common/toast/Toast.tsx
  src/pages/toolList/components/toolCard/ToolCard.tsx
Labels: 📍 Feat, 고은

#194 [Fix] 비회원의 경우, 커뮤니티 글쓰기 url 접근을 막는다
  src/components/common/button/circleButton/CircleButton.styled.ts
  src/components/common/button/circleButton/CircleButton.tsx
  src/pages/community/Community.tsx
  src/pages/communityWrite/CommunityWrite.tsx
Labels: ⚒️ Fix, 고은

#188 [Feat] 유저 닉네임 Input에 띄어쓰기 입력을 제한한다.
  src/components/common/input/nameInput/NameInput.styled.ts
  src/components/common/input/nameInput/NameInput.tsx
  src/components/common/input/nameInput/NamingInput.stories.tsx
  src/constants/nicknameCheck.ts
  src/pages/myPage/MyInfoPage.tsx
  src/pages/myPage/apis/queries.ts
  src/pages/myPage/components/namingInput/NamingInput.styled.ts
  src/pages/signUp/SignUp.tsx
  src/pages/signUp/components/namingInput/NamingInput.tsx
Labels: 📍 Feat

#196 [Feat] 툴리스트 페이지 - TanStack Query로 데이터 패칭을 최적화한다.
  src/apis/index.ts
  src/apis/tool/api.ts
  src/apis/tool/queries.ts
  src/pages/CommunityDetail/hooks/useToastOpen.ts
  src/pages/myPage/apis/queries.ts
  src/pages/toolList/ToolList.stories.tsx
  src/pages/toolList/ToolList.tsx
  src/pages/toolList/apis/api.ts
  src/pages/toolList/apis/queries.ts
  src/pages/toolList/components/searchBar/SearchBar.tsx
  src/pages/toolList/components/toolCard/ToolCard.styled.ts
  src/pages/toolList/components/toolCard/ToolCard.tsx
  src/pages/toolList/mocks/toolCard/ToolMockData.ts
  src/pages/toolList/types/ToolListType.ts
  src/pages/toolList/utils/ToolCard.utils.tsx
  src/pages/toolList/utils/toolCard/ToolCard.utils.tsx
  src/types/toolListBanner/ToolListBannerTypes.ts
Labels: 🔥 Refactor, 고은

#193 [Feat] 커뮤니티 글 작성 및 수정 페이지에 클립보드 이미지 붙여넣기 기능을 추가한다.
  src/components/common/postCard/PostCard.tsx
  src/hooks/index.ts
  src/hooks/useToastOpen.ts
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.tsx
  src/pages/CommunityDetail/hooks/index.ts
  src/pages/community/Community.tsx
  src/pages/communityModify/CommunityModify.tsx
  src/pages/communityModify/components/writingBody/WritingBody.tsx
  src/pages/communityModify/components/writingImg/WritingImg.tsx
  src/pages/communityWrite/CommunityWrite.tsx
  src/pages/communityWrite/components/writingBody/WritingBody.tsx
  src/pages/communityWrite/components/writingImg/WritingImg.tsx
  src/pages/myPage/MyFavoritePostPage.tsx
  src/pages/myPage/MyInfoPage.tsx
  src/pages/myPage/MyPostPage.tsx
  src/pages/myPage/MyToolPage.tsx
  src/pages/toolDetail/components/toolInfoCard/ToolInfoCard.tsx
  src/pages/toolList/components/toolCard/ToolCard.tsx
Labels: 📍 Feat, 채현

#191 [Feat] 사진 자세히 보기 컴포넌트에 닫기 버튼 인터랙션을 추가한다.
  src/assets/svgs/BtnWritingChipx56.tsx
  src/components/common/imgDetail/ImgDetail.styled.ts
  src/components/common/imgDetail/ImgDetail.tsx
Labels: 📍 Feat, 🎨 Design, 찬영

#197 [Feat] 툴 리스트 페이지 & 툴 상세페이지 - sessionStorage를 활용하여 스크롤 위치를 저장한다.
  src/pages/toolDetail/ToolDetail.tsx
  src/pages/toolDetail/components/community/Community.tsx
  src/pages/toolList/ToolList.tsx
  src/pages/toolList/components/toolCard/ToolCard.tsx
Labels: 🔥 Refactor, 찬영
