Repository Tool-daruda/daruda-frontend, pull requests merged in 2025-01, with the labels that each got.

#7 [Init] Global Style 설정
  package.json
  public/fonts/AppleSDGothicNeoB00.ttf
  public/fonts/AppleSDGothicNeoM00.ttf
  public/fonts/AppleSDGothicNeoR00.ttf
  public/fonts/AppleSDGothicNeoSB00.ttf
  src/App.tsx
  src/main.tsx
  src/styles/.keep
  src/styles/GlobalStyles.tsx
  src/styles/reset.ts
  yarn.lock
Labels: ⚙️ Init, 찬영

#14 [Init] Theme 세팅
  src/App.tsx
  src/main.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ⚙️ Init, 민

#12 [Init/#11] storybook 초기세팅
  .github/workflows/chromatic.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/provider.tsx
  index.html
  package-lock.json
  package.json
  src/components/Button.stories.ts
  src/components/Button.tsx
  src/components/button.css
  src/stories/Colors.stories.tsx
  src/stories/Fonts.stories.tsx
  src/stories/Introduction.mdx
  src/styles/theme.ts
  yarn.lock
Labels: ⚙️ Init, 채현

#24 [Feat] Spacing 공통 컴포넌트 구현
  src/components/common/spacing/Spacing.tsx
Labels: 📍 Feat, 채현

#19 [Feat] 공통 컴포넌트: 팝업
  .storybook/preview-body.html
  index.html
  public/svgs/img_modalcheck.svg
  public/svgs/img_modalexit.svg
  public/svgs/img_modalexit2.svg
  src/App.tsx
  src/assets/svgs/ImgModalcheck.tsx
  src/assets/svgs/ImgModalexit.tsx
  src/assets/svgs/ImgModalexit2.tsx
  src/assets/svgs/ImgPopupmodal84.tsx
  src/assets/svgs/index.ts
  src/components/common/modal/AlertModal.tsx
  src/components/common/modal/AlterModal.stories.tsx
  src/components/common/modal/AlterModal.styled.ts
  src/components/common/modal/component/DobbleModal.tsx
  src/components/common/modal/component/ModalBtns.tsx
  src/components/common/modal/component/ModalWrapper.tsx
  src/components/common/modal/component/SingleModal.tsx
  src/components/common/modal/component/index.ts
  src/components/common/modal/index.ts
  src/components/common/toast/Toast.stories.ts
  src/components/common/toast/Toast.styled.ts
  src/components/common/toast/Toast.tsx
  src/components/common/toast/toast.stories.ts
  src/styles/theme.ts
  tsconfig.app.json
  tsconfig.node.json
Labels: 📍 Feat, 💭 Style, 고은

#29 [Feat] Header & Footer 구현
  .storybook/provider.tsx
  public/svgs/ic_alarm_black_24.svg
  public/svgs/ic_arrow_down_black_24.svg
  public/svgs/ic_insta_gray_20.svg
  public/svgs/img_darudalogo_40.svg
  src/assets/.keep
  src/assets/svgs/IcAlarmBlack24.tsx
  src/assets/svgs/IcArrowDownBlack24.tsx
  src/assets/svgs/IcInstaGray20.tsx
  src/assets/svgs/ImgDarudalogo40.tsx
  src/assets/svgs/index.ts
  src/components/common/button/Button.stories.ts
  src/components/common/button/Button.tsx
  src/components/common/button/button.css
  src/components/common/footer/Footer.stories.tsx
  src/components/common/footer/Footer.styled.ts
  src/components/common/footer/Footer.tsx
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/toast/toast.stories.ts
  src/components/layout/Layout.stories.tsx
  src/components/layout/Layout.tsx
  src/components/layout/MyPageLayout.stories.tsx
  src/components/layout/MyPageLayout.tsx
  src/constants/.keep
  src/constants/headerState.ts
  tsconfig.app.json
Labels: 📍 Feat, 🎨 Design, 찬영

#31 [Feat] 드롭다운 공통 컴포넌트 구현
  package.json
  public/svgs/ic_overflow_gray_24.svg
  public/svgs/ic_overflow_gray_44.svg
  src/assets/svgs/IcOverflowGray24.tsx
  src/assets/svgs/IcOverflowGray44.tsx
  src/assets/svgs/index.ts
  src/components/common/chip/Chip.stories.tsx
  src/components/common/chip/Chip.styled.ts
  src/components/common/chip/Chip.tsx
  src/components/common/chip/chipColors.ts
  src/components/common/dropdown/DropDown.stories.tsx
  src/components/common/dropdown/DropDown.styled.ts
  src/components/common/dropdown/DropDown.tsx
  src/hooks/.keep
  src/hooks/index.ts
  src/hooks/useComponentContext.ts
  src/styles/theme.ts
Labels: 📍 Feat, 채현

#33 [Init] API 초기세팅
  package.json
  src/apis/.keep
  src/apis/errorResponse.ts
  src/apis/index.ts
  src/main.tsx
  yarn.lock
Labels: 📍 Feat, 채현

#37 [Feat] 마이페이지 툴 카드 컴포넌트 구현
  public/svgs/ic_bookmark_32.svg
  src/assets/svgs/IcBookmark32.tsx
  src/assets/svgs/ImgModalcheck.tsx
  src/assets/svgs/ImgModalexit.tsx
  src/assets/svgs/ImgModalexit2.tsx
  src/assets/svgs/ImgPopupmodal84.tsx
  src/assets/svgs/index.ts
  src/components/common/chip/Chip.styled.ts
  src/pages/myPage/components/toolCard/MyToolCard.stories.ts
  src/pages/myPage/components/toolCard/MyToolCard.styled.ts
  src/pages/myPage/components/toolCard/MyToolCard.tsx
  src/pages/myPage/utils/splitAndCountLines.ts
  src/stories/Fonts.stories.tsx
Labels: 📍 Feat, 채현

#30 [Feat] 공통 버튼 컴포넌트
  public/svgs/ic_bookmark_gray_24_dact.svg
  public/svgs/ic_cmtimg_gray_24.svg
  public/svgs/ic_comment_gray_24.svg
  public/svgs/ic_plus_white_20.svg
  public/svgs/ic_share_gray_24.svg
  public/svgs/img_upload_white_48.svg
  src/assets/svgs/IcBookmarkGray24Dact.tsx
  src/assets/svgs/IcCmtimgGray24.tsx
  src/assets/svgs/IcCommentGray24.tsx
  src/assets/svgs/IcPlusWhite20.tsx
  src/assets/svgs/IcShareGray24.tsx
  src/assets/svgs/ImgUploadWhite48.tsx
  src/assets/svgs/index.ts
  src/components/common/button/Button.stories.ts
  src/components/common/button/Button.tsx
  src/components/common/button/button.css
  src/components/common/button/circleButton/CircleButton.stories.tsx
  src/components/common/button/circleButton/CircleButton.styled.ts
  src/components/common/button/circleButton/CircleButton.tsx
  src/components/common/button/squareButton/SquareButton.stories.tsx
  src/components/common/button/squareButton/SquareButton.styled.ts
  src/components/common/button/squareButton/SquareButton.tsx
  src/styles/theme.ts
Labels: 📍 Feat, 🎨 Design, 민

#43 [Fix] layout 스토리북 수정
  src/components/layout/Layout.stories.tsx
  src/components/layout/MyPageLayout.stories.tsx
Labels: ⚒️ Fix, 🎨 Design, 찬영

#50 [Design/#47] Chip 컴포넌트 변경사항 적용
  src/components/common/chip/Chip.stories.tsx
  src/components/common/chip/Chip.styled.ts
  src/components/common/chip/chipColors.ts
Labels: 🎨 Design, 채현

#53 [Feat] 커뮤니티 목록 VIEW, 배너/ 커뮤니티 글 컴포넌트
  public/svgs/Img_Banner.svg
  public/svgs/ic_bookmark.svg
  public/svgs/ic_chevron.svg
  public/svgs/ic_comment_gray_24.svg
  public/svgs/img_textlogo.svg
  src/assets/images/img_banner_attached.png
  src/assets/svgs/BtnWritingChipxIcon.tsx
  src/assets/svgs/IcAlarmBlack24.tsx
  src/assets/svgs/IcArrowDownBlack24.tsx
  src/assets/svgs/IcBookmark.tsx
  src/assets/svgs/IcChevron.tsx
  src/assets/svgs/IcCommentGray24.tsx
  src/assets/svgs/IcInstaGray20.tsx
  src/assets/svgs/ImgBanner.tsx
  src/assets/svgs/ImgDarudalogo40.tsx
  src/assets/svgs/ImgTextlogo.tsx
  src/assets/svgs/index.ts
  src/components/common/button/circleButton/CircleButton.styled.ts
  src/components/common/button/squareButton/SquareButton.styled.ts
  src/components/common/dropdown/DropDown.stories.tsx
  src/components/common/dropdown/DropDown.styled.ts
  src/components/common/dropdown/DropDown.tsx
  src/components/common/modal/AlertModal.tsx
  src/components/common/modal/component/ModalWrapper.tsx
  src/pages/community/Community.stories.tsx
  src/pages/community/Community.style.ts
  src/pages/community/Community.tsx
  src/pages/community/components/banner/Banner.stories.tsx
  src/pages/community/components/banner/Banner.styles.ts
  src/pages/community/components/banner/Banner.tsx
  src/pages/community/components/card/Card.stories.ts
  src/pages/community/components/card/Card.styled.ts
  src/pages/community/components/card/Card.tsx
  src/pages/community/constants/constants.ts
  src/pages/community/hooks/index.ts
  src/pages/community/hooks/useModal.ts
  src/pages/community/mocks/index.ts
  src/pages/community/types/.keep
  src/pages/community/utils/formatContent.ts
  src/pages/community/utils/index.ts
Labels: 📍 Feat, 고은

#51 [Feat] 메인 리스트 상단 뷰 구현
  public/svgs/card_list_appcard.svg
  public/svgs/card_list_appcard_1.svg
  public/svgs/ic_search_gray_32.svg
  src/assets/svgs/CardListAppcard.tsx
  src/assets/svgs/CardListAppcard1.tsx
  src/assets/svgs/IcSearchGray32.tsx
  src/assets/svgs/index.ts
  src/pages/toolList/components/searchBar/SearchBar.stories.tsx
  src/pages/toolList/components/searchBar/SearchBar.styled.ts
  src/pages/toolList/components/searchBar/SearchBar.tsx
  src/pages/toolList/components/topBanner/TopBanner.stories.tsx
  src/pages/toolList/components/topBanner/TopBanner.styled.ts
  src/pages/toolList/components/topBanner/TopBanner.tsx
  src/pages/toolList/constants/searchBar/SearchBarCate.ts
  src/styles/theme.ts
Labels: 📍 Feat, 🎨 Design, 민

#57 [Feat] 마이페이지 글 메뉴 뷰 구현
  public/svgs/ic_mypage_bookmark_32.svg
  src/assets/svgs/IcMypageBookmark32.tsx
  src/assets/svgs/index.ts
  src/pages/myPage/MyFavoritePostPage.tsx
  src/pages/myPage/MyPostPage.tsx
  src/pages/myPage/Post.styled.ts
  src/pages/myPage/components/postCard/PostCard.stories.ts
  src/pages/myPage/components/postCard/PostCard.styled.ts
  src/pages/myPage/components/postCard/PostCard.tsx
  src/pages/myPage/mocks/myPostList.ts
  src/pages/myPage/stories/FavoritePostPage.stories.tsx
  src/pages/myPage/stories/FavoriteToolPage.stories.tsx
  src/pages/myPage/stories/MyPageStoryLayout.tsx
  src/pages/myPage/stories/MyPostPage.stories.tsx
Labels: 📍 Feat, 채현

#60 [Feat] 로그인 페이지 뷰 구현
  public/svgs/Ellipse 5276.svg
  public/svgs/KakaoVector.svg
  src/assets/svgs/ImgDarudalogo40.tsx
  src/assets/svgs/index.ts
  src/components/common/header/Header.tsx
  src/pages/login/KakaoAuth.stories.tsx
  src/pages/login/KakaoAuth.styled.ts
  src/pages/login/KakaoAuth.tsx
  src/pages/login/assets/Ellipse5276.tsx
  src/pages/login/assets/KakaoVector.tsx
  src/pages/login/assets/index.ts
  src/pages/login/components/confirmButton/ConfirmBtn.stories.tsx
  src/pages/login/components/confirmButton/ConfirmBtn.styled.ts
  src/pages/login/components/confirmButton/ConfirmBtn.tsx
  src/pages/signUp/SignUp.stories.tsx
  src/pages/signUp/SignUp.styled.ts
  src/pages/signUp/SignUp.tsx
  src/pages/signUp/components/affiliationButton/AffiliationBtn.stories.tsx
  src/pages/signUp/components/affiliationButton/AffiliationBtn.styled.ts
  src/pages/signUp/components/affiliationButton/AffiliationBtn.tsx
  src/pages/signUp/components/namingInput/NamingInput.stories.tsx
  src/pages/signUp/components/namingInput/NamingInput.styled.ts
  src/pages/signUp/components/namingInput/NamingInput.tsx
  src/pages/signUp/constants/affiliationOptions.ts
  src/routes/Router.tsx
  src/styles/theme.ts
Labels: 📍 Feat, 🎨 Design, 찬영

#64 [Design] Header 카테고리 UI 구현
  public/svgs/ic_arrow_down_black_24 copy.svg
  src/assets/svgs/IcArrowDownBlack24Copy.tsx
  src/assets/svgs/index.ts
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/header/category/Category.stories.tsx
  src/components/common/header/category/Category.styled.ts
  src/components/common/header/category/Category.tsx
Labels: 📍 Feat, 🎨 Design, 찬영

#67 [Design] design system 변경 사항 적용
  public/fonts/SFProDisplaybold.otf
  src/assets/svgs/BtnWritingChipxIcon.tsx
  src/assets/svgs/CardListAppcard.tsx
  src/assets/svgs/CardListAppcard1.tsx
  src/assets/svgs/IcAlarmBlack24.tsx
  src/assets/svgs/IcArrowDownBlack24.tsx
  src/assets/svgs/IcBookmark.tsx
  src/assets/svgs/IcBookmarkGray24Dact.tsx
  src/assets/svgs/IcChevron.tsx
  src/assets/svgs/IcChevronDownBlack16.tsx
  src/assets/svgs/IcCmtimgGray24.tsx
  src/assets/svgs/IcCommentGray24.tsx
  src/assets/svgs/IcInstaGray20.tsx
  src/assets/svgs/IcPlusWhite20.tsx
  src/assets/svgs/IcSearchGray32.tsx
  src/assets/svgs/IcShareGray24.tsx
  src/assets/svgs/ImgBanner.tsx
  src/assets/svgs/ImgTextlogo.tsx
  src/assets/svgs/ImgUploadWhite48.tsx
  src/assets/svgs/Union.tsx
  src/components/common/button/circleButton/CircleButton.styled.ts
  src/pages/myPage/components/postCard/PostCard.stories.ts
  src/stories/Colors.stories.tsx
  src/stories/Fonts.stories.tsx
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
Labels: 🎨 Design, 채현

#69 [Feat] 댓글 작성 Board 컴포넌트
  public/svgs/ic_cmtimg_gray_24.svg
  public/svgs/ic_imgdelete_gray_40.svg
  src/assets/svgs/Ellipse5276.tsx
  src/assets/svgs/Free.tsx
  src/assets/svgs/Half.tsx
  src/assets/svgs/IcCmtimgGray24.tsx
  src/assets/svgs/IcImgdeleteGray40.tsx
  src/assets/svgs/KakaoVector.tsx
  src/assets/svgs/Paid.tsx
  src/assets/svgs/index.ts
  src/components/common/button/circleButton/CircleButton.styled.ts
  src/components/common/button/squareButton/SquareButton.styled.ts
  src/components/common/button/squareButton/SquareButton.tsx
  src/pages/CommunityDetail/CommunityDetail.tsx
  src/pages/CommunityDetail/components/commentInput/CommentInput.stories.ts
  src/pages/CommunityDetail/components/commentInput/CommentInput.styled.ts
  src/pages/CommunityDetail/components/commentInput/CommentInput.tsx
  src/pages/CommunityDetail/components/inputButton/InputButton.styled.ts
  src/pages/CommunityDetail/components/inputButton/InputButton.tsx
  src/pages/CommunityDetail/constants/index.ts
  src/pages/CommunityDetail/hooks/index.ts
  src/pages/CommunityDetail/hooks/useImageUpload.ts
  src/pages/CommunityDetail/hooks/useTextInput.ts
  src/pages/community/Community.tsx
  src/pages/community/components/card/Card.tsx
  src/pages/community/hooks/useModal.ts
Labels: 📍 Feat, 고은

#82 [Feat] toolListPage 구현
  public/svgs/BlurLeft.svg
  public/svgs/LeftBlur.svg
  public/svgs/Rectangle 161126186.svg
  public/svgs/RightBlur.svg
  public/svgs/tooltip.svg
  src/assets/svgs/BlurLeft.tsx
  src/assets/svgs/LeftBlur.tsx
  src/assets/svgs/Rectangle161126186.tsx
  src/assets/svgs/RightBlur.tsx
  src/assets/svgs/Tooltip.tsx
  src/assets/svgs/index.ts
  src/pages/toolList/ToolList.stories.tsx
  src/pages/toolList/ToolList.styled.ts
  src/pages/toolList/ToolList.tsx
  src/pages/toolList/components/searchBar/SearchBar.stories.tsx
  src/pages/toolList/components/searchBar/SearchBar.styled.ts
  src/pages/toolList/components/searchBar/SearchBar.tsx
  src/pages/toolList/components/toggle/Toggle.stories.tsx
  src/pages/toolList/components/toggle/Toggle.styled.ts
  src/pages/toolList/components/toggle/Toggle.tsx
  src/pages/toolList/components/toolCard/ToolCard.stories.tsx
  src/pages/toolList/components/toolCard/ToolCard.styled.ts
  src/pages/toolList/components/toolCard/ToolCard.tsx
  src/pages/toolList/components/toolTip/ToolTip.stories.tsx
  src/pages/toolList/components/toolTip/ToolTip.styled.ts
  src/pages/toolList/components/toolTip/ToolTip.tsx
  src/pages/toolList/constants/searchBar/SearchBarCate.ts
  src/pages/toolList/mocks/toolCard/ToolMockData.ts
  src/pages/toolList/utils/toolCard/ToolCard.utils.tsx
Labels: 📍 Feat, 🎨 Design, 민

#73 [Feat] 커뮤니티 목록 페이지 VIEW
  src/components/common/banner/ToolListBanner.styled.ts
  src/components/common/banner/ToolListBanner.tsx
  src/components/common/chip/Chip.styled.ts
  src/pages/community/Community.style.ts
  src/pages/community/Community.tsx
Labels: 📍 Feat, 고은

#83 [Feat] 커뮤니티 세부 게시글 Card / 커뮤니티 세부 VIEW
  public/svgs/divider_community_cmt.svg
  public/svgs/ic_arrow_left_black_32.svg
  src/assets/svgs/DividerCommunityCmt.tsx
  src/assets/svgs/IcArrowLeftBlack32.tsx
  src/assets/svgs/index.ts
  src/components/common/postCard/PostCard.stories.ts
  src/components/common/postCard/PostCard.styled.ts
  src/components/common/postCard/PostCard.tsx
  src/pages/CommunityDetail/CommunityDetail.stories.tsx
  src/pages/CommunityDetail/CommunityDetail.styled.ts
  src/pages/CommunityDetail/CommunityDetail.tsx
  src/pages/CommunityDetail/components/comment/commentBoard/CommentBoard.styled.ts
  src/pages/CommunityDetail/components/comment/commentBoard/CommentBoard.tsx
  src/pages/CommunityDetail/components/comment/commentCard/CommentCard.styled.ts
  src/pages/CommunityDetail/components/comment/commentCard/CommentCard.tsx
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.stories.ts
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.styled.ts
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.tsx
  src/pages/CommunityDetail/components/input/inputButton/InputButton.styled.ts
  src/pages/CommunityDetail/components/input/inputButton/InputButton.tsx
  src/pages/CommunityDetail/hooks/useTextInput.ts
  src/pages/CommunityDetail/mocks/index.ts
  src/pages/community/Community.tsx
  src/pages/community/mocks/index.ts
  src/utils/handleScroll.ts
  src/utils/index.ts
Labels: 📍 Feat, 고은

#70 [Feat] 마이페이지 회원정보 뷰 구현
  src/pages/myPage/MyInfoPage.tsx
  src/pages/myPage/components/affiliationButton/AffiliationBtn.styled.ts
  src/pages/myPage/components/affiliationButton/AffiliationBtn.tsx
  src/pages/myPage/components/namingInput/NamingInput.styled.ts
  src/pages/myPage/components/namingInput/NamingInput.tsx
  src/pages/myPage/constants/affiliationOptions.ts
  src/pages/myPage/stories/MyInfoPage.stories.tsx
Labels: 📍 Feat, 채현

#79 [Feat] 404 페이지 구현
  public/svgs/error.svg
  src/assets/svgs/Error.tsx
  src/assets/svgs/index.ts
  src/pages/error/NotFound.stories.tsx
  src/pages/error/NotFound.styled.ts
  src/pages/error/NotFound.tsx
  src/routes/Router.tsx
Labels: 📍 Feat, 채현

#74 [Feat] 글쓰기 컴포넌트 구현
  public/svgs/Group 2085664966.svg
  public/svgs/PlusImg.svg
  public/svgs/btn_writing_arrowleft.svg
  public/svgs/ic_addimg_gray3_44.svg
  src/assets/lottie/loading.json
  src/assets/svgs/BtnWritingArrowleft.tsx
  src/assets/svgs/Group2085664966.tsx
  src/assets/svgs/IcAddimgGray344.tsx
  src/assets/svgs/IcArrowLeftBlack32.tsx
  src/assets/svgs/PlusImg.tsx
  src/assets/svgs/index.ts
  src/components/common/banner/ToolListBanner.styled.ts
  src/components/common/banner/ToolListBanner.tsx
  src/components/common/lottie/Loading.tsx
  src/pages/communityWrite/CommunityWrite.stories.tsx
  src/pages/communityWrite/CommunityWrite.styled.ts
  src/pages/communityWrite/CommunityWrite.tsx
  src/pages/communityWrite/components/writingBody/WritingBody.styled.ts
  src/pages/communityWrite/components/writingBody/WritingBody.tsx
  src/pages/communityWrite/components/writingImg/WritingImg.styled.ts
  src/pages/communityWrite/components/writingImg/WritingImg.tsx
  src/pages/communityWrite/components/writingTitle/WritingTitle.styled.ts
  src/pages/communityWrite/components/writingTitle/WritingTitle.tsx
  src/pages/toolList/components/toolCard/ToolCard.tsx
Labels: 📍 Feat, 🎨 Design, 민

#81 [Feat] 이미지 자세히 보기 팝업 구현
  public/svgs/btn_writing_chipx_56.svg
  public/svgs/ic_leftarrow_60.svg
  src/assets/svgs/BtnWritingChipx56.tsx
  src/assets/svgs/IcLeftarrow60.tsx
  src/assets/svgs/index.ts
  src/components/common/imgDetail/ImgDetail.stories.tsx
  src/components/common/imgDetail/ImgDetail.styled.ts
  src/components/common/imgDetail/ImgDetail.tsx
  src/styles/theme.ts
Labels: 📍 Feat, 채현

#88 [Feat] 툴 상세보기에 들어갈 커뮤니티 구현
  src/pages/toolDetail/components/community/Community.stories.tsx
  src/pages/toolDetail/components/community/Community.styled.ts
  src/pages/toolDetail/components/community/Community.tsx
Labels: 📍 Feat, 🎨 Design, 민

#93 [Fix] 툴리스트 페이지 오류 수정
  src/assets/svgs/index.ts
  src/pages/toolList/ToolList.styled.ts
  src/pages/toolList/components/searchBar/SearchBar.styled.ts
  src/pages/toolList/components/searchBar/SearchBar.tsx
Labels: ⚒️ Fix, 민

#89 [Feat] 모달 이미지 변경
  public/svgs/img_popup_delete_84.svg
  public/svgs/img_popup_logout_84.svg
  public/svgs/img_popup_logoutcheck_84.svg
  public/svgs/img_popup_quit_84.svg
  public/svgs/img_popup_withdrawal_84.svg
  src/assets/svgs/ImgPopupDelete84.tsx
  src/assets/svgs/ImgPopupLogout84.tsx
  src/assets/svgs/ImgPopupLogoutcheck84.tsx
  src/assets/svgs/ImgPopupQuit84.tsx
  src/assets/svgs/ImgPopupWithdrawal84.tsx
  src/assets/svgs/index.ts
  src/components/common/modal/AlterModal.stories.tsx
  src/components/common/modal/component/ModalBtns.tsx
  src/pages/communityWrite/CommunityWrite.tsx
  src/pages/error/NotFound.tsx
  src/pages/myPage/MyInfoPage.tsx
  src/pages/myPage/MyPostPage.tsx
  src/pages/myPage/components/tab/MyPageTab.tsx
Labels: 🎨 Design, 채현

#91 [Fix] line height 조정
  src/components/common/button/circleButton/CircleButton.styled.ts
  src/components/common/button/squareButton/SquareButton.styled.ts
  src/components/common/chip/Chip.styled.ts
  src/pages/toolDetail/components/toggle/Toggle.tsx
Labels: ⚒️ Fix, 채현

#94 [Feat] 온보딩 뷰
  public/svgs/img_darudalogo_50.svg
  public/svgs/img_textlogo177.svg
  src/assets/images/card_community.png
  src/assets/images/card_list1.png
  src/assets/images/card_list2.png
  src/assets/images/card_list3.png
  src/assets/images/card_popList1.png
  src/assets/images/card_popList2.png
  src/assets/images/card_popList3.png
  src/assets/images/card_popList4.png
  src/assets/images/card_popList5.png
  src/assets/lottie/daruda_scroll.json
  src/assets/svgs/ImgDarudalogo50.tsx
  src/assets/svgs/ImgTextlogo177.tsx
  src/assets/svgs/PlusImg.tsx
  src/assets/svgs/index.ts
  src/components/common/lottie/Scroll.tsx
  src/pages/error/NotFound.styled.ts
  src/pages/intro/Intro.tsx
  src/pages/intro/components/acrossSlide/AcorssSlide.styled.ts
  src/pages/intro/components/acrossSlide/AcrossSlide.tsx
  src/pages/intro/components/index.ts
  src/pages/intro/components/main/Main.styled.ts
  src/pages/intro/components/main/Main.tsx
  src/pages/intro/components/popList/PopList.styled.ts
  src/pages/intro/components/popList/PopList.tsx
  src/pages/intro/components/scrollPage/ScrollPage.styled.ts
  src/pages/intro/components/scrollPage/ScrollPage.tsx
  src/pages/intro/intro.styled.ts
Labels: 📍 Feat, 고은

#98 [Fix] 온보딩 페이지 스크롤 이슈 & 커뮤니티 페이지 툴 리스트바 간격 조정
  src/components/common/banner/ToolListBanner.styled.ts
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/pages/intro/Intro.tsx
  src/routes/Router.tsx
Labels: ⚒️ Fix, 고은

#105 [Fix] header 세부 수정
  public/svgs/ic_alarm_black_24.svg
  public/svgs/ic_profile_black_24.svg
  src/assets/svgs/IcAlarmBlack24.tsx
  src/assets/svgs/IcArrowDownBlack24.tsx
  src/assets/svgs/IcProfileBlack24.tsx
  src/assets/svgs/index.ts
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/header/category/Category.styled.ts
  src/components/common/header/category/Category.tsx
  src/components/layout/Layout.stories.tsx
  src/components/layout/Layout.tsx
  src/components/layout/MyPageLayout.tsx
  src/pages/intro/Intro.tsx
Labels: ⚒️ Fix, 🎨 Design, 찬영

#108 [Feat] 이미지 자세히 보기 연결
  src/components/common/postCard/PostCard.styled.ts
  src/components/common/postCard/PostCard.tsx
  src/pages/CommunityDetail/CommunityDetail.styled.ts
  src/pages/CommunityDetail/CommunityDetail.tsx
  src/pages/CommunityDetail/components/comment/commentBoard/CommentBoard.styled.ts
  src/pages/CommunityDetail/components/comment/commentBoard/CommentBoard.tsx
  src/pages/CommunityDetail/components/comment/commentCard/CommentCard.styled.ts
  src/pages/CommunityDetail/components/comment/commentCard/CommentCard.tsx
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.styled.ts
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.tsx
Labels: 📍 Feat, 고은

#109 [Feat] 온보딩 페이지
  package-lock.json
  package.json
  public/logo_landing.obj
  public/svgs/card_popList1.svg
  public/svgs/card_popList2.svg
  public/svgs/card_popList3.svg
  public/svgs/card_popList4.svg
  public/svgs/card_popList5.svg
  src/assets/lottie/daruda_scroll.json
  src/assets/lottie/render.json
  src/assets/lottie/scrolldown_.json
  src/assets/svgs/CardPopList1.tsx
  src/assets/svgs/CardPopList2.tsx
  src/assets/svgs/CardPopList3.tsx
  src/assets/svgs/CardPopList4.tsx
  src/assets/svgs/CardPopList5.tsx
  src/assets/svgs/index.ts
  src/components/common/button/circleButton/CircleButton.styled.ts
  src/components/common/button/circleButton/CircleButton.tsx
  src/components/common/lottie/IntroRender.tsx
  src/components/common/lottie/Scroll.tsx
  src/pages/intro/Intro.tsx
  src/pages/intro/components/acrossSlide/AcorssSlide.styled.ts
  src/pages/intro/components/index.ts
  src/pages/intro/components/last/Last.styled.ts
  src/pages/intro/components/last/Last.tsx
  src/pages/intro/components/last/Render3D.tsx
  src/pages/intro/components/main/Main.styled.ts
  src/pages/intro/components/main/Main.tsx
  src/pages/intro/components/popList/PopList.styled.ts
  src/pages/intro/components/popList/PopList.tsx
  src/pages/intro/components/scrollPage/ScrollPage.styled.ts
  yarn.lock
Labels: 📍 Feat, 고은

#106 [Feat] 글쓰기 페이지 API 연결
  public/svgs/img.svg
  public/svgs/img_symbollogo.svg
  src/apis/toolBanner/ToolBannerApi.ts
  src/assets/svgs/Img.tsx
  src/assets/svgs/ImgSymbollogo.tsx
  src/assets/svgs/index.ts
  src/components/common/banner/ToolListBanner.styled.ts
  src/components/common/banner/ToolListBanner.tsx
  src/constants/toolListBanner/ToolListBannerConstants.ts
  src/pages/communityWrite/CommunityWrite.styled.ts
  src/pages/communityWrite/CommunityWrite.tsx
  src/pages/communityWrite/apis/PostApi.ts
  src/pages/communityWrite/components/writingImg/WritingImg.styled.ts
  src/pages/communityWrite/components/writingImg/WritingImg.tsx
  src/pages/communityWrite/hooks/UseCommunityWrite.ts
  src/pages/communityWrite/types/PostType.ts
  src/pages/communityWrite/utils/FormDataUtils.ts
  src/types/toolListBanner/ToolListBannerTypes.ts
  src/utils/toolListBanner/ToolListBannerUtils.ts
Labels: 📍 Feat, 민

#113 [Feat] 커뮤니티 목록 페이지 QA
  public/svgs/img_banner_attached.svg
  src/assets/images/img_banner_attached.png
  src/assets/svgs/ImgBannerAttached.tsx
  src/assets/svgs/index.ts
  src/components/common/button/squareButton/SquareButton.styled.ts
  src/components/common/button/squareButton/SquareButton.tsx
  src/components/common/dropdown/DropDown.styled.ts
  src/components/common/postCard/PostCard.styled.ts
  src/components/common/postCard/PostCard.tsx
  src/pages/CommunityDetail/components/comment/commentBoard/CommentBoard.styled.ts
  src/pages/community/components/banner/Banner.styles.ts
  src/pages/community/components/banner/Banner.tsx
Labels: 🎨 Design, 고은

#120 [Feat] Header 카테고리 구현 및 UI 수정
  .storybook/provider.tsx
  .stylelintrc.json
  src/components/common/header/Header.styled.ts
  src/components/common/header/category/Category.styled.ts
  src/components/common/header/category/Category.tsx
  src/components/common/header/category/apis/api.ts
  src/components/common/header/category/apis/queries.ts
  src/components/common/header/category/types/index.ts
Labels: 📍 Feat, 찬영

#107 [Feat] 마이페이지 API 연결
  .storybook/preview.tsx
  .storybook/provider.tsx
  index.html
  public/favicon.ico
  public/logo.svg
  public/svgs/img_popup_nonebookmark_mypost.svg
  public/svgs/img_popup_nonebookmark_scrappost.svg
  public/svgs/img_popup_nonebookmark_scraptool.svg
  src/apis/board/api.ts
  src/apis/board/queries.ts
  src/apis/index.ts
  src/apis/tool/api.ts
  src/apis/tool/queries.ts
  src/apis/users/api.ts
  src/apis/users/queries.ts
  src/assets/svgs/ImgPopupNonebookmarkMypost.tsx
  src/assets/svgs/ImgPopupNonebookmarkScrappost.tsx
  src/assets/svgs/ImgPopupNonebookmarkScraptool.tsx
  src/assets/svgs/index.ts
  src/components/layout/MyPageLayout.tsx
  src/constants/nicknameCheck.ts
  src/pages/myPage/MyFavoritePostPage.tsx
  src/pages/myPage/MyInfoPage.tsx
  src/pages/myPage/MyPostPage.tsx
  src/pages/myPage/MyToolPage.tsx
  src/pages/myPage/Post.styled.ts
  src/pages/myPage/apis/api.ts
  src/pages/myPage/apis/queries.ts
  src/pages/myPage/components/namingInput/NamingInput.tsx
  src/pages/myPage/components/tab/MyPageTab.tsx
  src/pages/myPage/components/toolCard/MyToolCard.stories.ts
  src/pages/myPage/components/toolCard/MyToolCard.tsx
  src/pages/myPage/constants/affiliationOptions.ts
  src/pages/myPage/stories/FavoritePostPage.stories.tsx
  src/pages/myPage/stories/FavoriteToolPage.stories.tsx
  src/pages/myPage/stories/MyInfoPage.stories.tsx
  src/pages/myPage/stories/MyPostPage.stories.tsx
  src/pages/myPage/types/board.ts
  src/pages/myPage/types/info.ts
  src/pages/myPage/types/tool.ts
  src/stories/Colors.stories.tsx
  src/stories/Fonts.stories.tsx
  src/types/boardScrap.ts
  yarn.lock
Labels: 📍 Feat, 채현

#121 [Feat] head 작업
  .storybook/provider.tsx
  index.html
  package.json
  public/og_img.png
  public/og_img1.png
  public/og_img2.png
  src/components/common/title/Title.tsx
  src/components/layout/MyPageLayout.tsx
  src/main.tsx
  src/pages/CommunityDetail/CommunityDetail.tsx
  src/pages/community/Community.tsx
  src/pages/communityWrite/CommunityWrite.tsx
  src/pages/login/KakaoAuth.tsx
  src/pages/signUp/SignUp.tsx
  src/pages/toolDetail/ToolDetail.tsx
  yarn.lock
Labels: 📍 Feat, 채현

#115 [Feat] 상세페이지 API 연결
  src/apis/tool/getToolData.ts
  src/apis/tool/queries.ts
  src/components/common/imgDetail/ImgDetail.tsx
  src/components/common/postCard/PostCard.tsx
  src/pages/communityWrite/components/writingImg/WritingImg.tsx
  src/pages/intro/components/popList/PopList.tsx
  src/pages/login/KakaoRedirectHandler.tsx
  src/pages/login/apis/api.ts
  src/pages/login/apis/quaries.ts
  src/pages/signUp/apis/api.ts
  src/pages/signUp/types/index.ts
  src/pages/toolDetail/ToolDetail.tsx
  src/pages/toolDetail/apis/api.ts
  src/pages/toolDetail/apis/queries.ts
  src/pages/toolDetail/components/community/Community.tsx
  src/pages/toolDetail/components/coreFeatures/CoreFeature.tsx
  src/pages/toolDetail/components/planBox/PlanBox.tsx
  src/pages/toolDetail/components/planBox/plan/Plan.tsx
  src/pages/toolDetail/components/referenceVideo/ReferenceVideo.tsx
  src/pages/toolDetail/components/sidewing/Sidewing.styled.ts
  src/pages/toolDetail/components/sidewing/Sidewing.tsx
  src/pages/toolDetail/components/sidewing/SimilarToolCardList.tsx
  src/pages/toolDetail/components/sidewing/similarToolCard/SimilarToolCard.styled.ts
  src/pages/toolDetail/components/sidewing/similarToolCard/SimilarToolCard.tsx
  src/pages/toolDetail/types/index.ts
  src/pages/toolList/ToolList.tsx
  src/pages/toolList/components/searchBar/SearchBar.tsx
  src/pages/toolList/components/toolCard/ToolCard.tsx
  src/routes/Router.tsx
Labels: 📍 Feat, 찬영

#116 [Feat] 로그인&회원가입 API 연결
  public/images/background_img.png
  src/apis/index.ts
  src/main.tsx
  src/pages/login/KakaoAuth.stories.tsx
  src/pages/login/KakaoAuth.styled.ts
  src/pages/login/KakaoAuth.tsx
  src/pages/login/KakaoRedirectHandler..tsx
  src/pages/login/apis/api.ts
  src/pages/login/types/index.ts
  src/pages/signUp/SignUp.stories.tsx
  src/pages/signUp/SignUp.styled.ts
  src/pages/signUp/SignUp.tsx
  src/pages/signUp/apis/api.ts
  src/pages/signUp/components/affiliationButton/AffiliationBtn.styled.ts
  src/routes/Router.tsx
  yarn.lock
Labels: 📍 Feat, 찬영

#130 [Feat] toolListPage API연결
  public/svgs/backcards.svg
  src/assets/svgs/Backcards.tsx
  src/assets/svgs/index.ts
  src/components/common/chip/Chip.styled.ts
  src/components/common/chip/Chip.tsx
  src/components/common/header/category/Category.tsx
  src/pages/toolList/ToolList.tsx
  src/pages/toolList/apis/api.ts
  src/pages/toolList/components/searchBar/SearchBar.stories.tsx
  src/pages/toolList/components/searchBar/SearchBar.tsx
  src/pages/toolList/components/toolCard/ToolCard.styled.ts
  src/pages/toolList/components/toolCard/ToolCard.tsx
  src/pages/toolList/components/topBanner/TopBanner.styled.ts
  src/pages/toolList/components/topBanner/TopBanner.tsx
  src/pages/toolList/constants/searchBar/SearchBarCate.ts
  src/pages/toolList/utils/toolCard/ToolCard.utils.tsx
  src/styles/theme.ts
Labels: 📍 Feat, 민

#132 [Feat] ToolList BookMark API 연결
  src/pages/toolList/ToolList.styled.ts
  src/pages/toolList/components/toolCard/ToolCard.styled.ts
  src/pages/toolList/components/toolCard/ToolCard.tsx
  src/pages/toolList/types/ToolListType.ts
Labels: 📍 Feat, 민

#134 [Feat] 글쓰기 페이지 QA 반영
  src/components/common/banner/ToolListBanner.styled.ts
  src/pages/communityWrite/CommunityWrite.styled.ts
  src/pages/communityWrite/components/writingBody/WritingBody.styled.ts
  src/pages/communityWrite/components/writingImg/WritingImg.styled.ts
  src/pages/communityWrite/components/writingTitle/WritingTitle.styled.ts
Labels: 🎨 Design, 민

#137 [Fix] 자잘자잘한 에러 해결
  src/components/common/header/Header.tsx
  src/components/layout/Layout.stories.tsx
  src/components/layout/Layout.tsx
  src/components/layout/MyPageLayout.tsx
  src/pages/CommunityDetail/CommunityDetail.stories.tsx
  src/pages/community/Community.stories.tsx
  src/pages/communityModify/CommunityModify.tsx
  src/pages/communityModify/components/writingImg/WritingImg.tsx
  src/pages/communityModify/utils/FormDataUtils.ts
  src/pages/communityWrite/components/writingImg/WritingImg.tsx
  src/pages/error/NotFound.stories.tsx
  src/pages/intro/Intro.tsx
  src/pages/login/KakaoAuth.stories.tsx
  src/pages/myPage/MyFavoritePostPage.tsx
  src/pages/myPage/MyPostPage.tsx
  src/pages/myPage/MyToolPage.tsx
  src/pages/myPage/components/postCard/PostCard.tsx
  src/pages/myPage/components/toolCard/MyToolCard.tsx
  src/pages/myPage/stories/FavoritePostPage.stories.tsx
  src/pages/myPage/stories/FavoriteToolPage.stories.tsx
  src/pages/myPage/stories/MyInfoPage.stories.tsx
  src/pages/myPage/stories/MyPostPage.stories.tsx
  src/pages/signUp/SignUp.stories.tsx
  src/pages/toolDetail/ToolDetail.stories.tsx
  src/pages/toolDetail/ToolDetail.tsx
  src/pages/toolDetail/components/referenceVideo/ReferenceVideo.stories.tsx
  src/pages/toolDetail/components/referenceVideo/ReferenceVideo.tsx
  src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.stories.ts
  src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.styled.ts
  src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.tsx
Labels: ⚒️ Fix, 채현

#139 [Feat] 툴리스트페이지 QA 반영
  public/svgs/bigtext.svg
  src/assets/svgs/Bigtext.tsx
  src/assets/svgs/index.ts
  src/pages/toolList/components/searchBar/SearchBar.styled.ts
  src/pages/toolList/components/toolCard/ToolCard.styled.ts
  src/pages/toolList/components/toolCard/ToolCard.tsx
  src/pages/toolList/components/topBanner/TopBanner.tsx
Labels: ⚒️ Fix, 민

#129 [Feat] 상세페이지 API 연결 및 디자인 QA
  public/svgs/img__detail_freetool_98.svg
  src/apis/tool/queries.ts
  src/assets/svgs/ImgDetailFreetool98.tsx
  src/assets/svgs/index.ts
  src/components/common/banner/ToolListBanner.tsx
  src/components/common/scrollTop/ScrollTop.tsx
  src/components/layout/Layout.tsx
  src/components/layout/MyPageLayout.tsx
  src/pages/community/Community.tsx
  src/pages/toolDetail/ToolDetail.tsx
  src/pages/toolDetail/apis/api.ts
  src/pages/toolDetail/components/community/Community.stories.tsx
  src/pages/toolDetail/components/community/Community.styled.ts
  src/pages/toolDetail/components/community/Community.tsx
  src/pages/toolDetail/components/coreFeatures/CoreFeature.styled.ts
  src/pages/toolDetail/components/planBox/PlanBox.tsx
  src/pages/toolDetail/components/planBox/plan/Plan.styled.ts
  src/pages/toolDetail/components/planBox/plan/Plan.tsx
  src/pages/toolDetail/components/referenceVideo/ReferenceVideo.styled.ts
  src/pages/toolDetail/components/referenceVideo/ReferenceVideo.tsx
  src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.styled.ts
  src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.tsx
  src/pages/toolDetail/components/sidewing/Sidewing.styled.ts
  src/pages/toolDetail/components/sidewing/Sidewing.tsx
  src/pages/toolDetail/components/sidewing/SimilarToolCardList.tsx
  src/pages/toolDetail/components/sidewing/similarToolCard/SimilarToolCard.stories.tsx
  src/pages/toolDetail/components/sidewing/similarToolCard/SimilarToolCard.styled.ts
  src/pages/toolDetail/components/sidewing/similarToolCard/SimilarToolCard.tsx
  src/pages/toolDetail/components/toolInfoCard/ToolInfoCard.styled.ts
  src/pages/toolDetail/components/toolInfoCard/ToolInfoCard.tsx
  src/pages/toolDetail/components/toolInfoCard/types/index.ts
  src/pages/toolDetail/components/toolIntro/ToolIntro.tsx
Labels: 📍 Feat, 🎨 Design, 찬영

#142 [Fix] 이미지 썸네일 수정
  src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.tsx
Labels: ⚒️ Fix, 채현

#135 [Feat] 커뮤니티 댓글 작성 POST 및 세부 API 연결 테스트
  package.json
  public/logo.svg
  public/svgs/isBooked.svg
  src/apis/board/queries.ts
  src/apis/fetchPostList/api.ts
  src/apis/fetchPostList/queries.ts
  src/assets/svgs/IsBooked.tsx
  src/assets/svgs/index.ts
  src/components/common/banner/ToolListBanner.tsx
  src/components/common/button/circleButton/CircleButton.tsx
  src/components/common/button/squareButton/SquareButton.styled.ts
  src/components/common/button/squareButton/SquareButton.tsx
  src/components/common/postCard/PostCard.stories.ts
  src/components/common/postCard/PostCard.styled.ts
  src/components/common/postCard/PostCard.tsx
  src/components/common/toast/Toast.styled.ts
  src/components/common/toast/Toast.tsx
  src/pages/CommunityDetail/CommunityDetail.tsx
  src/pages/CommunityDetail/apis/deletePost/api.ts
  src/pages/CommunityDetail/apis/deletePost/queries.ts
  src/pages/CommunityDetail/apis/postComment/api.ts
  src/pages/CommunityDetail/apis/postComment/queries.ts
  src/pages/CommunityDetail/components/comment/commentBoard/CommentBoard.tsx
  src/pages/CommunityDetail/components/comment/commentCard/CommentCard.tsx
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.styled.ts
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.tsx
  src/pages/CommunityDetail/hooks/index.ts
  src/pages/CommunityDetail/hooks/useImageUpload.ts
  src/pages/CommunityDetail/hooks/useTextInput.ts
  src/pages/CommunityDetail/hooks/useToastOpen.ts
  src/pages/CommunityDetail/types/index.ts
  src/pages/community/Community.style.ts
  src/pages/community/Community.tsx
  src/pages/community/hooks/useModal.ts
  src/pages/intro/components/acrossSlide/AcrossSlide.tsx
  src/pages/intro/components/last/Last.tsx
  src/pages/intro/components/last/Render3D.tsx
  src/pages/intro/components/main/Main.tsx
  src/types/post.ts
  src/types/toolListBanner/ToolListBannerTypes.ts
  src/utils/toolListBanner/ToolListBannerUtils.ts
Labels: 📍 Feat, 고은

#148 [Feat] 상세페이지 QA 반영
  public/svgs/img_popup_nonebookmark_120.svg
  src/assets/svgs/ImgPopupNonebookmark120.tsx
  src/assets/svgs/index.ts
  src/components/common/chip/Chip.styled.ts
  src/components/common/chip/Chip.tsx
  src/pages/toolDetail/components/community/Community.styled.ts
  src/pages/toolDetail/components/community/Community.tsx
  src/pages/toolDetail/components/toolInfoCard/ToolInfoCard.styled.ts
  src/pages/toolDetail/components/toolInfoCard/ToolInfoCard.tsx
  src/routes/Router.tsx
Labels: 📍 Feat, 🎨 Design, 찬영

#150 [Feat] 회원가입 페이지 중복확인 로직 구현
  src/pages/signUp/SignUp.styled.ts
  src/pages/signUp/SignUp.tsx
  src/pages/signUp/apis/api.ts
  src/pages/signUp/components/namingInput/NamingInput.styled.ts
  src/pages/signUp/components/namingInput/NamingInput.tsx
Labels: 📍 Feat, 🎨 Design, 찬영

#152 [Feat] skeleton, bookmark
  src/components/common/banner/ToolListBanner.tsx
  src/components/skeleton/ToolBannerSkeleton.styled.ts
  src/components/skeleton/ToolBannerSkeleton.tsx
  src/pages/toolList/components/toolCard/ToolCard.styled.ts
  src/pages/toolList/components/toolCard/ToolCard.tsx
Labels: 📍 Feat, ⚒️ Fix, 민

#155 [Fix] 디테일 수정
  src/pages/toolList/ToolList.styled.ts
  src/pages/toolList/ToolList.tsx
Labels: ⚒️ Fix, 민

#158 [Feat] 상세페이지 QA 반영
  src/assets/svgs/index.ts
  src/pages/CommunityDetail/hooks/useToastOpen.ts
  src/pages/toolDetail/components/toolInfoCard/ToolInfoCard.tsx
Labels: 📍 Feat, 🎨 Design, 찬영

#159 [Fix] 툴 리스트 오류 수정
  src/pages/community/Community.tsx
  src/pages/toolList/ToolList.styled.ts
  src/pages/toolList/ToolList.tsx
Labels: ⚒️ Fix, 민

#161 [Fix] QA 반영 사항 커뮤니티 오류 해결
  src/apis/board/api.ts
  src/components/common/postCard/PostCard.tsx
  src/pages/CommunityDetail/apis/deletePost/api.ts
  src/pages/CommunityDetail/apis/postComment/api.ts
  src/pages/CommunityDetail/apis/postComment/queries.ts
  src/pages/CommunityDetail/components/comment/commentCard/CommentCard.tsx
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.tsx
  src/pages/CommunityDetail/constants/index.ts
  src/pages/CommunityDetail/hooks/useImageUpload.ts
  src/pages/community/Community.tsx
Labels: ⚒️ Fix, 고은

#170 [Design] 배너 색상 추가
  src/pages/toolList/components/topBanner/TopBanner.styled.ts
  src/pages/toolList/components/topBanner/TopBanner.tsx
Labels: 🎨 Design, 찬영

#173 [Fix] 댓글 비회원일 경우 입력 조차 안 되게
  public/svgs/img_speak_bubble.svg
  src/assets/svgs/ImgSpeakBubble.tsx
  src/assets/svgs/index.ts
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.styled.ts
  src/pages/CommunityDetail/components/input/commentInput/CommentInput.tsx
  src/pages/CommunityDetail/hooks/useTextInput.ts
Labels: ⚒️ Fix, 고은
