Repository Tool-daruda/daruda-frontend, pull requests merged in 2025-04, with the labels that each got.

#205 [Feat] 믹스패널을 도입한다 .
  .storybook/provider.tsx
  package.json
  src/hoc/useAnalytics.tsx
  src/main.tsx
  src/pages/toolDetail/components/referenceVideo/ReferenceVideo.tsx
  src/pages/toolDetail/components/referenceVideo/videoCard/VideoCard.tsx
  src/pages/toolDetail/components/sidewing/Sidewing.tsx
  src/pages/toolDetail/components/toolInfoCard/ToolInfoCard.tsx
  src/pages/toolDetail/components/toolIntro/ToolIntro.tsx
  src/pages/toolList/components/searchBar/SearchBar.tsx
  src/pages/toolList/components/toolCard/ToolCard.tsx
  tsconfig.app.json
  yarn.lock
Labels: 📍 Feat, 고은

#209 [FIx] AnalyticsProvider 단의 분기처리를 롤백한다.
  src/hoc/useAnalytics.tsx
Labels: ⚒️ Fix, 고은

#207 [Feat] 마이페이지 닉네임 특수문자 입력을 제한한다.
  src/components/common/input/nameInput/NameInput.tsx
Labels: 📍 Feat, 채현

#216 [Fix] 로그인 헤더 Content-Type을 변경한다.
  src/apis/auth/auth.api.ts
  src/pages/toolList/apis/api.ts
  yarn.lock
Labels: ⚒️ Fix

#213 [Feat] husky 커밋 메시지 관련 규칙을 강화한다.
  .eslintrc.json
  .husky/_/prepare-commit-msg
  .husky/commit-msg
  .stylelintrc.json
  commitlint.config.cjs
  package.json
  src/components/common/input/nameInput/NameInput.tsx
  yarn.lock
Labels: 📍 Feat, 고은
